name: colab_deped-dashboard
channels:
  - conda-forge
  - defaults
dependencies:
  - ansi2html=1.9.1
  - asttokens=2.0.5
  - blas=1.0
  - blinker=1.9.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.1
  - dash=2.14.2
  - debugpy=1.8.11
  - decorator=5.1.1
  - et_xmlfile=1.1.0
  - executing=0.8.3
  - flask=3.0.3
  - flask-compress=1.13
  - idna=3.7
  - importlib-metadata=8.5.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - itsdangerous=2.2.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - libffi=3.4.4
  - libsass=0.22.0
  - libsodium=1.0.18
  - markupsafe=3.0.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - narwhals=1.31.0
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openpyxl=3.1.5
  - openssl=3.4.1
  - packaging=24.2
  - pandas=2.2.3
  - parso=0.8.4
  - pip=25.0
  - platformdirs=3.10.0
  - plotly=6.0.1
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pysocks=1.7.1
  - python=3.11.11
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2024.1
  - pywin32=308
  - pyzmq=26.2.0
  - requests=2.32.3
  - retrying=1.3.3
  - setuptools=72.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tenacity=9.0.0
  - tk=8.6.14
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2025a
  - ucrt=10.0.22621.0
  - urllib3=2.3.0
  - vc=14.42
  - vc14_runtime=14.42.34438
  - vs2015_runtime=14.42.34438
  - wcwidth=0.2.5
  - werkzeug=3.0.6
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
